name: Vercel upload

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: add package token
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_REPO_TOKEN }}" >> .npmrc
      - name: cache node modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: add vercel config
        run: mkdir .vercel && echo '{"orgId":"ag3RFq2oDccVGXnn3EvGb9bt","projectId":"Qme3jeYMxmpNRX6SQaCsokDtr7nXEVuiTFmUaAsXLEuJiD"}' > .vercel/project.json
      - name: install
        run: yarn
      - name: run vercel
        run: vercel --token ${{secrets.VERCEL_TOKEN}}
