name: Deploy to development

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: add package token
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_REPO_TOKEN }}" >> .npmrc

      - name: cache node modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: install
        run: yarn

      - name: add vercel config
        run: mkdir .vercel && echo '{"orgId":"${{secrets.VERCEL_ORG_ID}}","projectId":"${{secrets.VERCEL_PROJECT_ID_DEV}}"}' > .vercel/project.json

      - name: run vercel
        run: vercel --token ${{secrets.VERCEL_TOKEN}} --prod
